#!/usr/bin/python3
"""creating a class that  defines a string
"""
class Rectangle:
    """
    an empty class
    """
    def __init__(self, width=0, height=0):
        self.__width = width
        self.__height = height
    @property 
    def width(self, value):
        return self.
